### ISSUE TITLE
Учесть Toaster в SSR

### ISSUE THREAD

**Issue by andreyvolokitin** [Minneapolis-7/game#113]
Склоняюсь, что лучше перенести Toaster в Page. Тогда и SSR исправлять не надо, и идеологически будет правильно — .page подразумевается как рут всего, и например имеет `overflow: hidden`, чтобы ничего не вылезло наружу. С тостером во вне это нарушается

**Comment by DariaZherebtsova** [comment]
Я не против. Были сложности из-за того, что Page ребенок LoginPage, а не родитель. Надо подумать как из LoginPage добавлять тосты.

**Comment by kotosha-real** [comment]
В таком случае, при переходе со страницы на страницу `Page` будет перерендирваться и старые тосты будут сбрасываться. Поправьте, если это не так

**Comment by DariaZherebtsova** [comment]
А старые тосты нужны на новой странице?) 
Где их хранить, если они будут в Page? в контексте то уже не получиться передавать

**Comment by andreyvolokitin** [comment]
Можно хранить в `AppContext`, а в `Page` только `Toaster` перенести, потом забирать тосты из `AppContext`. Про перерендер не могу сказать пока

**Comment by andreyvolokitin** [comment]
Речь про то что при переключении страниц показанные на экране тосты скроются или с ними произойдёт что-то нежелательное? Наверно тогда оставить как сейчас, тосты хоть и формально не нужны на новой странице, но кажется что будет более ожидаемо если они будут жить независимо от переключения страниц
